### ISSUE TITLE
현재까지 todo 및 논의사항 정리

### ISSUE THREAD

**Issue by Jeseong-Jeong** [swsnu/swpp2020-team14#40]
TODO:

- [x] 게시글 UI 수정, 
- [x] 게시글 preview (list page에서)
- [x] signup 이후 자동 로그인구현, 
- [x] 폰트 샘플 파일 제작 및 UI 수정,
- [x] 폰트 정보 입력,
- [x] 사진 업로드 후 백엔드에서 리포트 계산하는 시간 handling해주기,
- [x] 메인페이지 구상 및 구현
- [ ] 로그인 유저의 차별성 구상 및 구현하기,
- [ ] 글씨 detection 기능 추가 및 report page에서 띄워주기,
- [ ] 테스팅 완성

TO DISCUSS:
- [ ] 게시글에 사진이 꼭 있어야 하는지?
- [x] Photo edit 기능은 필요할지?
- [x] Photo detail page와 report page를 병합해야 할지?
- [x] 메인페이지의 UI/UX를 어떻게 할지?
- [ ] 로그인 유저의 차별성 기능을 뭐로 할지?
